image: alpine:latest

pages:
  stage: deploy
  script:
  - mkdir -p public/.well-known/acme-challenge/
  - cp le/*  public/.well-known/acme-challenge/
  artifacts:
    paths:
    - public
  only:
  - master
